import Vue from 'vue'
import {
  Button,
  Tabbar,
  TabbarItem,
  Dialog,
  Icon,
  NavBar,
  Search,
  Tab,
  Tabs,
  Toast,
  Swipe,
  SwipeItem,
  GoodsAction,
  GoodsActionIcon,
  GoodsActionButton,
  Cell,
  CellGroup,
  Sidebar,
  SidebarItem,
  Card,
  Stepper,
  SubmitBar,
  Checkbox,
  SwipeCell,
  AddressList,
  AddressEdit,
  Area,
  Form,
  Field,
  List,
  Sticky,
  Skeleton,
  Sku,
  Overlay,
  Uploader,
  ActionSheet,
  Picker,
  DatetimePicker
} from 'vant'

Vue.use(Button)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Dialog)
Vue.use(Icon)
Vue.use(NavBar)
Vue.use(Search)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Toast)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(GoodsAction)
Vue.use(GoodsActionIcon)
Vue.use(GoodsActionButton)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Sidebar)
Vue.use(SidebarItem)
Vue.use(Card)
Vue.use(Stepper)
Vue.use(SubmitBar)
Vue.use(Checkbox)
Vue.use(SwipeCell)
Vue.use(AddressList)
Vue.use(AddressEdit)
Vue.use(Area)
Vue.use(Form)
Vue.use(Field)
Vue.use(List)
Vue.use(Sticky)
Vue.use(Skeleton)
Vue.use(Sku)
Vue.use(Overlay)
Vue.use(Uploader)
Vue.use(ActionSheet)
Vue.use(Picker)
Vue.use(DatetimePicker)
